name: Run Python script
on: 
  push:
    branches:
        - master
        - 'master/**'   
  #   # paths:
  #   #   - '**.txt'
  # pull_request:
  #   branches:   
  #     - new_devops_branch
  #     - 'main/**'

env:
  SCRIPT_NAME: longets_cons_num.py
  NUMBER: 00000222211111155577

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Run python script
        run: |
          cd scripts
          python $SCRIPT_NAME $NUMBER

#comment for feature 1